artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion #create a directory in artifacts by the name data_ingestion
  dataset_name: yasserh/housing-prices-dataset #dataset from kaggle api token key downloaded dataset
  local_data_file: artifacts/data_ingestion/housing-prices-dataset.zip #downloading in compessed format to the place where the local_data_file specifies
  unzip_dir: artifacts/data_ingestion #extracting the data from the compressed folder to feed to the model

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion/Housing.csv
  all_schema:
    - price
    - area
    - bedrooms
    - bathrooms
    - stories
    - mainroad
    - guestroom
    - basement
    - hotwaterheating
    - airconditioning
    - parking
    - prefarea
    - furnishingstatus